extensions:
  health_check:
    endpoint: 0.0.0.0:13133

receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318

processors:
  attributes/privacy:
    actions:
      - key: net.peer.ip
        action: delete
      - key: http.user_agent
        action: delete
  batch:

exporters:
  otlp:
    endpoint: jaeger:4317
    tls:
      insecure: true

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [attributes/privacy, batch]
      exporters: [otlp]
